language: java
jdk:
  - oraclejdk8

install: ant

script:
 - ant integracion-continua
  
notifications:
  email:
    recipients:
     - nico.garofalo98@gmail.com
    on_failure: always
    on_success: always
      
after_success:
  - bash <(curl -s https://codecov.io/bash)

